### ISSUE TITLE
PortAudio?

### ISSUE THREAD

**Issue by chakravala** [JeffFessler/Sound.jl#2]
why is this separate from PortAudio?

**Comment by chakravala** [comment]
I don't have any stakes in this, but I reccommend you to make a PR yourself
if you think you're going to settle on PortAudio, since this is such a
small function.

Personally, I am banned from contributing to all official Julia
organizations and websites, so there is no way I can make a PR or
contribute.

So I understand where you're coming from, the official Julia repositories
are not very inclusive, I definitely don't contribute to them either.

**Comment by JeffFessler** [comment]
For the record, I did try: https://github.com/JuliaAudio/PortAudio.jl/issues/95

I understand the reasons given there.
